### ISSUE TITLE
Missing grunt packages

### ISSUE THREAD

**Issue by Kuzirashi** [Wildhoney/EmberDroplet#86]
Ubuntu 15.04 package v0.9.6
~~~~
$ npm install ember-droplet --verbose
...
> ember-droplet@0.9.6 postinstall xxx/node_modules/ember-droplet
> bower install && grunt build

>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
>> Local Npm module "grunt-contrib-concat" not found. Is it installed?
>> Local Npm module "grunt-contrib-yuidoc" not found. Is it installed?
>> Local Npm module "grunt-contrib-jasmine" not found. Is it installed?
>> Local Npm module "grunt-contrib-copy" not found. Is it installed?
Warning: Task "yuidoc" not found. Use --force to continue.

Aborted due to warnings.
npm verb unsafe-perm in lifecycle false
npm info ember-droplet@0.9.6 Failed to exec postinstall script
npm verb unlock done using /home/xxx/.npm/_locks/ember-droplet-5154568c7bf86d04.lock for xxx/node_modules/ember-droplet
npm verb stack Error: ember-droplet@0.9.6 postinstall: `bower install && grunt build`
npm verb stack Exit status 3
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1008:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
npm verb pkgid ember-droplet@0.9.6
npm verb cwd xxx
npm ERR! Linux 3.19.0-12-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "ember-droplet" "--verbose"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ember-droplet@0.9.6 postinstall: `bower install && grunt build`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the ember-droplet@0.9.6 postinstall script 'bower install && grunt build'.
npm ERR! This is most likely a problem with the ember-droplet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-droplet
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/ember-droplet
npm info preuninstall ember-droplet@0.9.6
npm info uninstall ember-droplet@0.9.6
npm verb unbuild rmStuff ember-droplet@0.9.6 from xxx/node_modules
npm info postuninstall ember-droplet@0.9.6
npm verb gentlyRm vacuuming xxx/node_modules/ember-droplet

npm ERR! Please include the following file with any support request:
npm ERR!     xxx/npm-debug.log
$
~~~~
Installing via npm packages that are reported not found doesn't fix problem.

**Comment by Wildhoney** [comment]
Please try again with `v0.9.7`: `npm install ember-droplet@0.9.7 --verbose` :+1:

**Comment by Kuzirashi** [comment]
Works. :) But npm install timeouts badly on some packages...

**Comment by Wildhoney** [comment]
Excellent! :beers: 

Could be an issue with `npm`, although [everything seems to be functioning fine](http://status.npmjs.org/) for the moment, or your own connection.
